export const persons = [
  {
    id: 1,
    name: "Aino Virtanen",
    title: "HR Manager",
    salary: 4200,
    phone: "040-1234567",
    email: "aino.virtanen@example.com",
    animal: "Owl",
    startDate: "2025-04-01",
    location: "Helsinki",
    department: "Human Resources",
    skills: ["Recruiting", "Communication", "Employee Relations"],
  },
  {
    id: 2,
    name: "Markus Laine",
    title: "Software Developer",
    salary: 4800,
    phone: "050-7654321",
    email: "markus.laine@example.com",
    animal: "Wolf",
    startDate: "2020-01-15",
    location: "Tampere",
    department: "Engineering",
    skills: ["JavaScript", "React", "Node.js"],
  },
  {
    id: 3,
    name: "Elina Mäkinen",
    title: "Marketing Specialist",
    salary: 3900,
    phone: "044-9876543",
    email: "elina.makinen@example.com",
    animal: "Fox",
    startDate: "2019-07-22",
    location: "Helsinki",
    department: "Marketing",
    skills: ["SEO", "Content Creation", "Analytics"],
  },
  {
    id: 4,
    name: "Jari Korhonen",
    title: "Financial Analyst",
    salary: 5100,
    phone: "041-1237894",
    email: "jari.korhonen@example.com",
    animal: "Snake",
    startDate: "2017-03-10",
    location: "Espoo",
    department: "Finance",
    skills: ["Budgeting", "Forecasting", "Data Analysis"],
  },
  {
    id: 5,
    name: "Laura Niemi",
    title: "UX Designer",
    salary: 4600,
    phone: "045-9988776",
    email: "laura.niemi@example.com",
    animal: "Cat",
    startDate: "2021-06-01",
    location: "Helsinki",
    department: "Design",
    skills: ["Figma", "User Research", "Prototyping"],
  },
  {
    id: 6,
    name: "Antti Salmi",
    title: "IT Support Specialist",
    salary: 3500,
    phone: "046-3322110",
    email: "antti.salmi@example.com",
    animal: "Dog",
    startDate: "2016-11-30",
    location: "Turku",
    department: "IT",
    skills: ["Troubleshooting", "Networking", "Customer Support"],
  },
  {
    id: 7,
    name: "Sanna Räsänen",
    title: "Product Manager",
    salary: 5800,
    phone: "050-1239087",
    email: "sanna.rasanen@example.com",
    animal: "Eagle",
    startDate: "2019-02-25",
    location: "Helsinki",
    department: "Product",
    skills: ["Roadmapping", "Agile", "Stakeholder Management"],
  },
  {
    id: 8,
    name: "Timo Koskinen",
    title: "DevOps Engineer",
    salary: 5300,
    phone: "040-5556677",
    email: "timo.koskinen@example.com",
    animal: "Bear",
    startDate: "2020-10-10",
    location: "Oulu",
    department: "Engineering",
    skills: ["AWS", "CI/CD", "Docker"],
  },
  {
    id: 9,
    name: "Riikka Lehtinen",
    title: "Legal Advisor",
    salary: 6200,
    phone: "043-7865432",
    email: "riikka.lehtinen@example.com",
    animal: "Panther",
    startDate: "2015-09-01",
    location: "Helsinki",
    department: "Legal",
    skills: ["Contracts", "Compliance", "Risk Management"],
  },
  {
    id: 10,
    name: "Mikko Hämäläinen",
    title: "Data Scientist",
    salary: 6000,
    phone: "047-7890123",
    email: "mikko.hamalainen@example.com",
    animal: "Raven",
    startDate: "2015-01-01",
    location: "Tampere",
    department: "Data",
    skills: ["Python", "Machine Learning", "Data Visualization"],
  },
];
